language: go
go: 
 - stable
before_install:
  # required packages
  - sudo apt-get install libudev-dev libusb-dev -y
  # hidapi
  - git clone https://github.com/OpenHMD/hidapi.git
  - cd hidapi
  - ./bootstrap
  - ./configure
  - make
  - sudo make install
  - cd ../
  # OpenHMD
  cd OpenHMD
  - meson ./build
  - ninja -C ./build/
  - sudo ninja -C ./build/ install
# Actual build
script: go build
