language: go
go: stable
install:
  - sudo apt update && sudo apt install libudev-dev libusb-1.0-0-dev libtool ninja-build python3-pip python3.5 -y
  - pip3 install --user meson
  - export PATH=$PATH:~/.local/bin
  - git clone https://github.com/OpenHMD/OpenHMD.git && git clone https://github.com/OpenHMD/hidapi.git
  - cd hidapi
  - autoreconf --install --verbose --force && ./configure
  - make && sudo make install
  - cd .. && cd OpenHMD
  - meson ./build
  - ninja -C ./build/ && sudo ninja -C ./build/ install
  - cd .. && rm -rf hidapi OpenHMD
script:
  - go build
  - go test -v
