language: go
go: stable
dist: xenial
addons:
  apt:
    packages:
      - git
      - libhidapi-dev
      - libhidapi-libusb0
      - libtool
      - python3.5
      - python3-pip
    update: true
install:
  - sudo pip3 install meson 
  - git clone https://github.com/OpenHMD/OpenHMD.git
  - cd OpenHMD
  - meson ./build
  - ninja -C ./build && sudo ninja -C ./build/ install
  - cd .. && rm -rf OpenHMD
script:
  - go build
  - go test -v