dist: xenial
language: go
go: 
 - stable
install: sh .travis-deps.sh
# From now on, Travis takes over.
jobs:
  include:
    - stage: build
      script: go build
    - stage: test
      script: go test -v
stages:
- build
- test