dist: xenial
language: go
go: stable
jobs:
  include:
    - stage: install
      script: sh .travis-deps.sh
    - stage: build
      script: go build
    - stage: test
      script: go test -v
stages:
- install
- build
- test