dist: xenial
language: go
go: 
 - stable
before_install:
  # required packages
  - sudo apt-get install libudev-dev libusb-1.0-0-dev meson ninja-build libtool -y
  # hidapi
  - git clone https://github.com/OpenHMD/hidapi.git
  - cd hidapi
  - ./bootstrap
  - ./configure
  - make
  - sudo make install
  - cd ..
  # OpenHMD
  - cd OpenHMD
  - cmake . 
  - make
  - sudo make install
  - cd ..
# Actual build
script: go build
