language: go
go: latest
dist: xenial
addons:
  apt:
    packages:
      - git
      - libhidapi-dev
      - libhidapi-libusb0
      - ninja-build
      - python3.5
      - python3-pip
      - python3-setuptools
    update: true
before_install: sudo pip3 install meson
install:
  - git clone https://github.com/OpenHMD/OpenHMD.git
  - cd OpenHMD
  - meson ./build
  - ninja -C ./build
  - sudo ninja -C ./build/ install
  - cd ..
  - rm -rf OpenHMD
script: go test -v
