// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package openhmd

/*
#include "OpenHMD/include/openhmd.h"
#include "handler.h"

#cgo LDFLAGS: -L. -lopenhmd
*/
import "C"

import (
	"strings"
	"unsafe"
)

// Create makes an OpenHMD context.
// Returns nil if the context can't allocate memory.
func Create() *Context {
	ctx := C.ohmd_ctx_create()

	if ctx == nil {
		return nil
	}

	return &Context{c: ctx}
}

// Destroy removes the current OpenHMD context.
// Note: Your context will be nulled and all devices associated with the context are automatically closed.
func (c *Context) Destroy() {
	C.ohmd_ctx_destroy(c.c)
}

// GetError gets the last error as a human readable string.
func (c *Context) GetError() string {
	return C.GoString(C.ohmd_ctx_get_error(c.c))
}

// Update updates the current context
// to fetch the values for the devices handled by a context.
func (c *Context) Update() {
	C.ohmd_ctx_update(c.c)
}

// Probe for devices.
// Returns the number of devices found on the system.
func (c *Context) Probe() int {
	return int(C.ohmd_ctx_probe(c.c))
}

// GetString fetches a string from OpenHMD.
func GetString(desc StringDescription) (StatusCode, string) {
	var value **C.char
	code := StatusCode(C.ohmd_gets(C.ohmd_string_description(desc), value))

	// I can't len() over a **C.Char, sadly
	str := make([]string, StringSize)
	for i, s := range (*[1 << 30]*C.char)(unsafe.Pointer(value))[:StringSize:StringSize] {
		str[i] = C.GoString(s)
	}

	return code, strings.Join(str, " ")
}

// ListGetString gets device description from enumeration list index.
func (c *Context) ListGetString(deviceIndex int, value StringValue) string {
	return C.GoString(C.ohmd_list_gets(c.c, C.int(deviceIndex), C.ohmd_string_value(value)))
}

// ListGetInt gets integer value from enumeration list index.
func (c *Context) ListGetInt(deviceIndex int, value IntValue) (StatusCode, int) {
	var val C.int
	code := StatusCode(C.ohmd_list_geti(c.c, C.int(deviceIndex), C.ohmd_int_value(value), &val))
	return code, int(val)
}

// ListOpenDevice opens a device.
func (c *Context) ListOpenDevice(index int) *Device {
	return &Device{c: C.ohmd_list_open_device(c.c, C.int(index))}
}

// ListOpenDeviceSettings opens a device with additional settings provided.
func (c *Context) ListOpenDeviceSettings(index int, settings DeviceSettings) *Device {
	return &Device{c: C.ohmd_list_open_device_s(c.c, C.int(index), settings.c)}
}

// CreateSettings creates a device settings instance.
func (c *Context) CreateSettings() *DeviceSettings {
	settings := C.ohmd_device_settings_create(c.c)

	if settings == nil {
		return nil
	}

	return &DeviceSettings{c: settings}
}

// Destroy destroys a device settings instance.
func (s *DeviceSettings) Destroy() {
	C.ohmd_device_settings_destroy(s.c)
}

// Close closes the current device.
func (d *Device) Close() StatusCode {
	return StatusCode(C.ohmd_close_device(d.c))
}

// GetFloatSingle fetches one float value.
func (d *Device) GetFloatSingle(value FloatValue, input float32) (StatusCode, float32) {
	var val C.float
	code := StatusCode(C.getfloatsingle(d.c, C.ohmd_float_value(value), val))
	return code, float32(val)
}

// GetFloatMulti fetches multiple float values.
func (d *Device) GetFloatMulti(value FloatValue, length int) (StatusCode, []float32) {
	val := make([]C.float, length)
	code := StatusCode(C.setfloatmulti(d.c, C.ohmd_float_value(value), val))

	vals := make([]float32, length)
	for i, v := range val {
		vals[i] = float32(v)
	}

	return code, vals
}

// GetIntSingle fechtes one int value.
func (d *Device) GetIntSingle(value IntValue, input int) (StatusCode, int) {
	var val C.int
	code := StatusCode(C.getintsingle(d.c, C.ohmd_int_value(value), val))
	return code, int(val)
}

// GetIntMulti fetches multiple int values.
func (d *Device) GetIntMulti(value IntValue, length int) (StatusCode, []int) {
	val := make([]C.int, length)
	code := StatusCode(C.getintmulti(d.c, C.ohmd_int_value(value), val))

	vals := make([]int, length)
	for i, v := range val {
		vals[i] = int(v)
	}

	return code, vals
}

// SetFloatSingle sets one float value.
func (d *Device) SetFloatSingle(value FloatValue, input float32) StatusCode {
	return StatusCode(C.setfloatsingle(d.c, C.ohmd_float_value(value), C.float(input)))
}

// SetFloatMulti sets multiple float values.
func (d *Device) SetFloatMulti(value FloatValue, input []float32) StatusCode {
	val := make([]C.float, len(input))
	for i, v := range input {
		val[i] = C.float(v)
	}

	return StatusCode(C.setfloatmulti(d.c, C.ohmd_float_value(value), val))
}

// SetIntSingle sets one int value.
func (d *Device) SetIntSingle(value IntValue, input int) StatusCode {
	return StatusCode(C.setintsingle(d.c, C.ohmd_int_value(value), C.int(input)))
}

// SetIntMulti sets multiple int values.
func (d *Device) SetIntMulti(value IntValue, input []int) StatusCode {
	val := make([]C.int, len(input))
	for i, v := range input {
		val[i] = C.int(v)
	}

	return StatusCode(C.setintmulti(d.c, C.ohmd_int_value(value), val))
}

// SetData sets direct data for a device.
func (d *Device) SetData(value DataValue, input *interface{}) StatusCode {
	return StatusCode(C.ohmd_device_set_data(d.c, C.ohmd_data_value(value), unsafe.Pointer(input)))
}

// GetVersion fetches OpenHMD's version.
func GetVersion() (int, int, int) {
	var major, minor, patch C.int
	C.ohmd_get_version(&major, &minor, &patch)

	return int(major), int(minor), int(patch)
}

// RequireVersion checks that the library is compatible with the required version.
// Returns StatusOkay if compatible, else StatusUnsupported.
func RequireVersion(major, minor, patch int) StatusCode {
	return StatusCode(C.ohmd_require_version(C.int(major), C.int(minor), C.int(patch)))
}
