// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package openhmd

//#cgo LDFLAGS: -L. -lopenhmd
//#include "OpenHMD/include/openhmd.h"
import "C"

// CreateContext creates a context.
func CreateContext() *Context {
	return &Context{
		c: C.ohmd_ctx_create(),
	}
}

// Destroy destroys the context.
func (c *Context) Destroy() {
	C.ohmd_ctx_destroy(c.c)
}

// Probe -
func (c *Context) Probe() int {
	return int(C.ohmd_ctx_probe(c.c))
}

// ListOpenDevice -
func (c *Context) ListOpenDevice(index int) *Device {
	return &Device{
		c: C.ohmd_list_open_device(c.c, C.int(index)),
	}
}

// ListGetS -
func (c *Context) ListGetS(deviceIndex int, value StringValue) string {
	return C.GoString(C.ohmd_list_gets(c.c, C.int(deviceIndex), C.ohmd_string_value(value)))
}

// ListGetI -
func (d *Device) ListGetI(value IntValue, out int) int {
	val := C.int(out)
	return int(C.ohmd_device_geti(d.c, C.ohmd_int_value(value), &val))
}

// ListGetF -
func (d *Device) ListGetF(value FloatValue, out int) int {
	val := C.float(out)
	return int(C.ohmd_device_getf(d.c, C.ohmd_float_value(value), &val))
}

// Update -
func (c *Context) Update() {
	C.ohmd_ctx_update(c.c)
}
