// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package openhmd

//#cgo LDFLAGS: -L. -lopenhmd
//#include "OpenHMD/include/openhmd.h"
import "C"

// StatusCode - Response status codes.
type StatusCode int

// StringValue - String values to fetch information.
type StringValue int

// StringDescription - String descriptions for StringValues.
type StringDescription int

// ControlHint - Control hints.
type ControlHint int

// ControlType - Control types.
type ControlType int

// FloatValue - Floating point values.
type FloatValue int

// IntValue - Integer values.
type IntValue int

// DataValue - Data values.
type DataValue int

// IntSettings - Integer-based settings.
type IntSettings int

// DeviceClass - Device classes for OpenHMD devices.
type DeviceClass int

// DeviceFlags - Device flags for OpenHMD devices.
type DeviceFlags int

// Context holds contextial data.
type Context struct {
	c *C.struct_ohmd_context
}

// Device defines a OpenHMD device, like a HMD.
type Device struct {
	c *C.struct_ohmd_device
}

// DeviceSettings represents arguments for a Device.
type DeviceSettings struct {
	c *C.struct_ohmd_device_settings
}
